language: php

php:
  - 7.0
  - 7.1

env:
  global:
    - setup=stable
    - laravel=5.x

sudo: false

install:
  - composer require illuminate/support:${laravel} --no-update
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit
